language: node_js
node_js:
  - "6"
addons:
  chrome: stable
services:
  - mongodb
before_script:
  - touch .env
  - npm install -g @angular/cli
  - npm run build
script:
  - npm run test:server
  - ng lint
  - ng test --single-run
  - ng e2e
